#!/bin/bash
export HOME=/root
export TERM=xterm

red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
green() { echo -e "\\033[32;1m${*}\\033[0m"; }
red() { echo -e "\\033[31;1m${*}\\033[0m"; }

clear
function send_log() {
TIMES="10"
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT2="
<code>───────────────────────────</code>
                              ✨SUCCES RENEW  VMESS✨
<code>───────────────────────────</code>
<code>USERNAME       : $user</code>
<code>Expired On     : $exp4</code>
<code>───────────────────────────</code>
"
curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT2&parse_mode=html" $URL >/dev/null
}    
read -rp "Input Username : " user
    # Periksa apakah pengguna ada
    if ! grep -qw "^### $user" "/etc/xray/config.json"; then
        echo -e "        User Tidak Ditemukan       \E[0m"
else
    read -p "Expired (days): " masaaktif
    exp4=$(date -d "$masaaktif days" +"%Y-%m-%d")
    sed -i "/### $user/c\### $user $exp4" /etc/xray/config.json
    sed -i "/## $user/c\## $user $exp4" /etc/xray/config.json
    sed -i "/### $user/c\### $user $exp4" /root/akun/vmess/.vmess.conf
    systemctl restart xray > /dev/null 2>&1
    send_log
fi